Improve test coverage WIP
apex-enterprise-patterns/at4dx pull request #41
Opened 2020-12-28 01:44 UTC by stohn777

2021-03-17 01:10 UTC, ImJohnMDaniel requested changes

2021-03-17 01:10 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-application-factory/TestSelectorMethod.cls
> +public inherited sharing class TestSelectorMethod
@stohn777, please move this class to be an inner class of `ApplicationSObjectSelectorTest`.  Just make the `TestSelectorMethod.Parameters` class as a inner class of `ApplicationSObjectSelectorTest` as well.

2021-03-17 01:10 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-application-factory/TestOnlyAccounts.cls
> +public with sharing class TestOnlyAccounts
@stohn777, please move `TestOnlyAccounts` to be a inner class of `ApplicationFactoryTest` and move the `Constructor` and `ITestOnlyAccounts` as direct inner classes of `ApplicationFactoryTest`.

2021-03-17 01:10 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-application-factory/TestOnlyClasses.cls
> +public class TestOnlyClasses
@stohn777, please rename this to be `ApplicationFactoryTestOnlyClasses`

2021-03-17 01:41 UTC, stohn777 commented on sfdx-source/core/main/classes/framework-application-factory/Application.cls
> +            if (injector_return instanceOf IApplicationSObjectDomain)
During stub-based mocking.  This is the case that Mr. Chaplin raised where a stub-based mock domain cannot have be an instance of `IConstructable2`.

2021-03-17 01:41 UTC, stohn777 commented on sfdx-source/core/test/classes/framework-application-factory/TestOnlyAccounts.cls
> +public with sharing class TestOnlyAccounts
Illegal in Apex with an inner class having an `implements`.  Something to that effect; can't remember the compile error verbatim.

2021-03-17 01:41 UTC, stohn777 commented on sfdx-source/core/test/classes/framework-application-factory/TestOnlyClasses.cls
> +public class TestOnlyClasses
Agreed.

2021-03-17 01:41 UTC, stohn777 commented on sfdx-source/core/test/classes/framework-application-factory/TestSelectorMethod.cls
> +public inherited sharing class TestSelectorMethod
Illegal in Apex with an inner class having an `implements`.  Something to that effect; can't remember the compile error verbatim.

2021-03-17 01:41 UTC, stohn777 commented on sfdx-source/core/test/classes/framework-platform-event-distributor/TestPlatformEventsConsumer.cls
> +public class TestPlatformEventsConsumer
Although this has only one class in it, the pattern is consistent with `TestOnlyClasses` or soon to be `ApplicationFactoryTestOnlyClasses`.

2021-03-21 00:38 UTC, stohn777 commented on sfdx-source/core/test/classes/framework-application-factory/TestSelectorMethod.cls
> +public inherited sharing class TestSelectorMethod
Not `implements`.  By putting this class in the other, then we have 3 levels of classes which is illegal in Apex.

2021-03-21 00:38 UTC, stohn777 commented on sfdx-source/core/test/classes/framework-application-factory/TestOnlyAccounts.cls
> +public with sharing class TestOnlyAccounts
Not `implements`.  By putting this class in the other, then we have 3 levels of classes which is illegal in Apex.

2021-03-21 01:08 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-application-factory/TestOnlyAccounts.cls
> +public with sharing class TestOnlyAccounts
@stohn777 You would just move the third-tier inner classes as independent second-tier inner classes.

2021-03-21 01:09 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-application-factory/TestSelectorMethod.cls
> +public inherited sharing class TestSelectorMethod
@stohn777 You would just move the third-tier inner classes as independent second-tier inner classes.

2021-03-21 01:10 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-platform-event-distributor/TestPlatformEventsConsumer.cls
> +public class TestPlatformEventsConsumer
I hear ya but I am trying to clutter  up the framework with independent "test" classes.  Better to hide them in as inner classes

2021-03-26 22:54 UTC, stohn777 reviewed
@ImJohnMDaniel   The method at `Application.cls` line 320 appears unused and deleting it would increase our code coverage, in addition to removing dead code.  Can you recall anything about it?

2021-03-27 14:08 UTC, ImJohnMDaniel commented
> @ImJohnMDaniel The method at `Application.cls` line 320 appears unused and deleting it would increase our code coverage, in addition to removing dead code. Can you recall anything about it?

@stohn777 -- I think that you are right and that it is not need.  I am removing it now.

2021-03-27 15:39 UTC, ImJohnMDaniel commented
> @ImJohnMDaniel The method at `Application.cls` line 320 appears unused and deleting it would increase our code coverage, in addition to removing dead code. Can you recall anything about it?

@stohn777 -- specifically which method are you referring to?

2021-03-27 17:04 UTC, stohn777 commented
> 
> 
> > @ImJohnMDaniel The method at `Application.cls` line 320 appears unused and deleting it would increase our code coverage, in addition to removing dead code. Can you recall anything about it?
> 
> @stohn777 -- specifically which method are you referring to?

Hmm?  The line number must've been from a different version.  This method ...
`private static Type determineClassType( Object instantiatedClass )`

2021-03-27 17:43 UTC, stohn777 commented on sfdx-source/core/main/classes/framework-application-factory/Application.cls
> +            if (injector_return instanceOf IApplicationSObjectDomain)
Referring to this issue.
https://github.com/apex-enterprise-patterns/at4dx/issues/25

2021-03-27 22:45 UTC, ImJohnMDaniel approved these changes

2021-03-27 22:45 UTC, merged