added code coverage for PlatformEventDistributorDIModule
apex-enterprise-patterns/at4dx pull request #53
Opened 2021-04-13 18:29 UTC by madiraza

2021-04-13 21:02 UTC, stohn777 requested changes
Thank you greatly for your help with code coverage and testing.

2021-04-13 21:02 UTC, stohn777 commented on sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorDIModuleTest.cls
> +        System.assertEquals(
@madiraza @bspeelm 
Please touch the indenting in this Assert, and I'm good.

2021-04-13 22:12 UTC, bspeelm commented on sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorDIModuleTest.cls
> +        System.assertEquals(
@stohn777 no problem should look better now.

2021-04-14 00:50 UTC, stohn777 commented on sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorDIModuleTest.cls
> +        System.assertEquals(
@bspeelm  After a more attentive look, it seems this test is more about code coverage, which is okay, but may I suggest a slightly different Assert that actually means something?  First, externally expose the 'warningMessage' variable in the DIModule.  Second Assert that it's blank after valid CMD records are provided to the class.  With that, more tests could provide invalid CMD records and Assert the 'warningMessage' is appropriate.

2021-04-14 15:48 UTC, bspeelm commented on sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorDIModuleTest.cls
> +        System.assertEquals(
@stohn777 Let me know what you think of this. I exposed the warning message through a private static variable. I suppose the warningMessage itself could be completely moved out of the configure() method but I didn't want to be destructive.

2021-04-14 16:23 UTC, stohn777 commented on sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorDIModuleTest.cls
> +        System.assertEquals(
@bspeelm That will certainly do the job.

Personally I wouldn't use the "magic string" as the expected value; only Assert that it's populated or not.  BUT we can consider cleaning-up the messaging functionality later.

2021-04-14 16:23 UTC, stohn777 approved these changes

2021-04-14 17:52 UTC, ImJohnMDaniel approved these changes

2021-04-14 17:53 UTC, merged