Winter 23 api update and update test classes to use new Assert class
apex-enterprise-patterns/at4dx pull request #68
Opened 2022-12-02 20:58 UTC by chazwatkins

2022-12-03 23:15 UTC, ImJohnMDaniel requested changes

2022-12-03 23:15 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls
> +        System.Assert.areEqual(true, matchEventBusAndCategoryResult.wasTestPlatformEventsConsumerCalled, 'Platform events consumer was not called');
Please change to `System.Assert.isTrue()` method

2022-12-03 23:15 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls
> +        System.Assert.areEqual(true, matchEventBusAndEventNameResult.wasTestPlatformEventsConsumerCalled, 'Platform events consumer was not called');
Please change to `System.Assert.isTrue()` method

2022-12-03 23:15 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls
> +        System.Assert.areEqual(true, matchEventBusResult.wasTestPlatformEventsConsumerCalled, 'Platform events consumer was not called');
Please change to `System.Assert.isTrue()` method

2022-12-03 23:15 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls
> +        System.Assert.areEqual(false, pedInstance.jobIdList.isEmpty(), 'Job id was not found in the job id list');
Please change to `System.Assert.isFalse()` method

2022-12-03 23:28 UTC, chazwatkins commented
@ImJohnMDaniel  Good catches.  With so many changes, I figured there would be a few left.

2022-12-03 23:31 UTC, chazwatkins commented
The updates are finished as requested

2022-12-03 23:38 UTC, ImJohnMDaniel requested changes

2022-12-03 23:38 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls
> +        System.Assert.isTruematchEventBusAndCategoryResult.wasTestPlatformEventsConsumerCalled, 'Platform events consumer was not called');
@chazwatkins -- minor syntax correction needed here please.

2022-12-03 23:38 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls
> +        System.Assert.isTruematchEventBusAndEventNameResult.wasTestPlatformEventsConsumerCalled, 'Platform events consumer was not called');
same here

2022-12-03 23:38 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls
> +        System.Assert.isTruematchEventBusResult.wasTestPlatformEventsConsumerCalled, 'Platform events consumer was not called');
same here

2022-12-03 23:38 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls
> +        System.Assert.isTruepedInstance.jobIdList.isEmpty(), 'Job id was not found in the job id list');
same here

2022-12-03 23:45 UTC, chazwatkins commented on sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls
> +        System.Assert.isTruematchEventBusAndCategoryResult.wasTestPlatformEventsConsumerCalled, 'Platform events consumer was not called');
Oof, don't know how I managed that one.  I'll update it now

2022-12-03 23:52 UTC, chazwatkins commented
Apologies for the typos.  The changes are now complete

2022-12-04 13:38 UTC, ImJohnMDaniel approved these changes

2022-12-04 23:53 UTC, stohn777 approved these changes

2023-01-16 21:51 UTC, chazwatkins reviewed
Resolving all the reviewable issues.  I believe all the requested changes are complete.

> Reviewed 53 of 55 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/at4dx/68#-:-NLwYyYpDmekJ0cCD5zL:b-pquv0n)* status: all files reviewed, 8 unresolved discussions (waiting on @ImJohnMDaniel)

___
*[`sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls` line 117 at r1](https://reviewable.io/reviews/apex-enterprise-patterns/at4dx/68#-NIJcT8jjOWTnpfgOP-1-r1-117:-NLwY-2v7jofZdB5UvIa:b-896fix) ([raw file](https://github.com/apex-enterprise-patterns/at4dx/blob/5aa96e26d6771ac0e309d91b8cee0bd27e08c4e1/sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls#L117)):*
<details><summary><i>Previously, ImJohnMDaniel (John M. Daniel) wrote…</i></summary><blockquote>

Please change to `System.Assert.isTrue()` method
</blockquote></details>

Done.
___
*[`sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls` line 158 at r1](https://reviewable.io/reviews/apex-enterprise-patterns/at4dx/68#-NIJcT8jjOWTnpfgOP-1-r1-158:-NLwY7ql5moyuYeognp3:b-896fix) ([raw file](https://github.com/apex-enterprise-patterns/at4dx/blob/5aa96e26d6771ac0e309d91b8cee0bd27e08c4e1/sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls#L158)):*
<details><summary><i>Previously, ImJohnMDaniel (John M. Daniel) wrote…</i></summary><blockquote>

Please change to `System.Assert.isTrue()` method
</blockquote></details>

Done.
___
*[`sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls` line 199 at r1](https://reviewable.io/reviews/apex-enterprise-patterns/at4dx/68#-NIJcT8jjOWTnpfgOP-1-r1-199:-NLwYuNx6g97yyh0kl0P:b-896fix) ([raw file](https://github.com/apex-enterprise-patterns/at4dx/blob/5aa96e26d6771ac0e309d91b8cee0bd27e08c4e1/sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls#L199)):*
<details><summary><i>Previously, ImJohnMDaniel (John M. Daniel) wrote…</i></summary><blockquote>

Please change to `System.Assert.isTrue()` method
</blockquote></details>

Done.
___
*[`sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls` line 241 at r1](https://reviewable.io/reviews/apex-enterprise-patterns/at4dx/68#-NIJcT8jjOWTnpfgOP-1-r1-241:-NLwYw6x5IC5exdSKa0m:b-896fix) ([raw file](https://github.com/apex-enterprise-patterns/at4dx/blob/5aa96e26d6771ac0e309d91b8cee0bd27e08c4e1/sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls#L241)):*
<details><summary><i>Previously, ImJohnMDaniel (John M. Daniel) wrote…</i></summary><blockquote>

Please change to `System.Assert.isFalse()` method
</blockquote></details>

Done.
___
*[`sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls` line 158 at r2](https://reviewable.io/reviews/apex-enterprise-patterns/at4dx/68#-NIJcT8jjOWTnpfgOP-1-r2-158:-NLwYsjTDjRimGoYCh-x:b-896fix) ([raw file](https://github.com/apex-enterprise-patterns/at4dx/blob/4777ff4f1efe9fe8e7587b436261b5d6d6808675/sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls#L158)):*
<details><summary><i>Previously, ImJohnMDaniel (John M. Daniel) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls` line 199 at r2](https://reviewable.io/reviews/apex-enterprise-patterns/at4dx/68#-NIJcT8jjOWTnpfgOP-1-r2-199:-NLwYv1xA1VLwKgxB5ZK:b-896fix) ([raw file](https://github.com/apex-enterprise-patterns/at4dx/blob/4777ff4f1efe9fe8e7587b436261b5d6d6808675/sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls#L199)):*
<details><summary><i>Previously, ImJohnMDaniel (John M. Daniel) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls` line 241 at r2](https://reviewable.io/reviews/apex-enterprise-patterns/at4dx/68#-NIJcT8jjOWTnpfgOP-1-r2-241:-NLwYwTY3MOskkz9lZb-:b-896fix) ([raw file](https://github.com/apex-enterprise-patterns/at4dx/blob/4777ff4f1efe9fe8e7587b436261b5d6d6808675/sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls#L241)):*
<details><summary><i>Previously, ImJohnMDaniel (John M. Daniel) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-16 21:52 UTC, chazwatkins commented
*[`sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls` line 117 at r2](https://reviewable.io/reviews/apex-enterprise-patterns/at4dx/68#-NIJcT8jjOWTnpfgOP-1-r2-117:-NLwZDso5OOTa0qAazCv:b-896fix) ([raw file](https://github.com/apex-enterprise-patterns/at4dx/blob/4777ff4f1efe9fe8e7587b436261b5d6d6808675/sfdx-source/core/test/classes/framework-platform-event-distributor/PlatformEventDistributorTest.cls#L117)):*
<details><summary><i>Previously, chazwatkins (Chaz Watkins) wrote…</i></summary><blockquote>

Oof, don't know how I managed that one.  I'll update it now
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-16 21:52 UTC, chazwatkins reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/at4dx/68#-:-NLwZNn_-_3ToXN0CZCj:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @ImJohnMDaniel)



<!-- Sent from Reviewable.io -->

2023-01-17 15:58 UTC, merged

2023-01-17 15:59 UTC, ImJohnMDaniel commented
@chazwatkins -- Thanks for the PR.  

Reviewable is interesting, for certain.  Not required on the AEP repos but some of us do us it.